### ISSUE TITLE
Questions/suggestions about this package

### ISSUE THREAD

**Issue by gep13** [app-iron/Cake.NSpec#1]
I just happened to be looking through the NuGet packages that involve the word "cake" (I do this in order to keep this list up to date: https://github.com/cake-build/website/issues/149) and I happened to notice this new one.  Thank you very much for joining the Cake community, I am sure that this will be a very welcome addin!

In order to help let people know about this addin, I would encourage you (when you are ready) to submit a PR to this repository to get you addin listed here:

http://cakebuild.net/addins

You can see a recent PR that did just that here:

https://github.com/cake-build/website/pull/222

The automatic documentation that we offer on cakebuild.net is driven by the XML documentation that is discussed here:

http://cakebuild.net/docs/contributing/documentation

If you look at any of the addin's in the Cake-Contrib organisation (https://github.com/cake-contrib), you will see examples of doing this.  For example, Cake.Gem would be a good one to look at.

On the topic of the Cake-Contrib organisation, have you read this:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

The outcome of that blog post is that almost all the Cake Addin's on NuGet have opted to add the cake-contrib user as a co-owner of the package.  Currently, we have 84 packages under the cake-contrib user (https://www.nuget.org/profiles/cake-contrib).  It would be great if we could get this addin there as well.

I noticed that you have used the name of `iron.apps.Cake.NSpec` for the NuGet package.  While there is nothing wrong with this, from purely a consistency point of view, it would be good if the package name were simply Cake.NSpec.  What do you think?

Please feel free to reach out if you have any questions about the above!

Thanks again for joining the Cake Community!

**Comment by iron-apeiron** [comment]
So i reworked the Package Name to Cake.NSpec as you proposed. I also added cake-contrib as Package Owner to the Cake.NSpec Nuget Package. 

After the next step of adding Documentation i will submit a pull request to the cake-build/website repository

**Comment by gep13** [comment]
@iron-apeiron that is great news!  Thank you very much for doing that!

**Comment by gep13** [comment]
While I remember...  Should this package: https://www.nuget.org/packages/iron.apps.Cake.NSpec/ be unlisted?  Or perhaps deprecated, in favour of the Cake.NSpec package?

**Comment by iron-apeiron** [comment]
good catch, i forgot to do that after i published the new one. 
Fixed it now :)

**Comment by gep13** [comment]
@iron-apeiron thanks!
